
import { supabase } from '../lib/supabase';
import { Patient, SupabaseCustomer } from '../types';

export const patientService = {
    async fetchPatients(): Promise<Patient[]> {
        const { data, error } = await supabase
            .from('Cliente')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) {
            console.error('Error fetching patients:', error);
            throw error;
        }

        return (data as SupabaseCustomer[]).map(mapCustomerToPatient);
    },

    async createPatient(patient: Omit<Patient, 'id' | 'lastVisit'>): Promise<void> {
        // We map local Patient back to Supabase 'Cliente'
        // Note: ID and created_at are auto-generated by Supabase
        const newCustomer = {
            nome: patient.name,
            telefoneWhatsapp: patient.phone,
            email: patient.email,
            plano: patient.plano
            // Other fields left empty as requested
        };

        const { error } = await supabase
            .from('Cliente')
            .insert(newCustomer);

        if (error) throw error;
    },

    async updatePatient(id: string, patient: Partial<Patient>): Promise<void> {
        const updates: any = {};
        if (patient.name) updates.nome = patient.name;
        if (patient.phone) updates.telefoneWhatsapp = patient.phone;
        if (patient.email) updates.email = patient.email;
        if (patient.plano) updates.plano = patient.plano;
        // status update if needed map to database fields

        const { error } = await supabase
            .from('Cliente')
            .update(updates)
            .eq('id', id);

        if (error) throw error;
    },

    async deletePatient(id: string): Promise<void> {
        const { error } = await supabase
            .from('Cliente')
            .delete()
            .eq('id', id);

        if (error) throw error;
    },

    subscribeToPatients(onChanges: () => void) {
        return supabase
            .channel('custom-all-channel')
            .on(
                'postgres_changes',
                { event: '*', schema: 'public', table: 'Cliente' },
                () => {
                    onChanges();
                }
            )
            .subscribe();
    }
};

// Mapper utility
function mapCustomerToPatient(customer: SupabaseCustomer): Patient {
    // Determine name: prefer nome_completo, fallback to nome, fallback to 'Sem Nome'
    const name = customer.nome_completo || customer.nome || 'Paciente sem nome';

    // Determine status (Simple logic for now)
    // Check if botAtivo is 'true', '1', 'active' etc. 
    // Adjust based on real data observation.
    const isActive = customer.botAtivo === 'true' || customer.status_lead_no_crm !== 'arquivado';

    return {
        id: customer.id ? customer.id.toString() : '',
        name: name,
        phone: customer.telefoneWhatsapp?.replace('@s.whatsapp.net', '') || '',
        email: customer.email,
        plano: customer.plano,
        status: isActive ? 'Ativo' : 'Ativo', // Defaulting to Ativo for visibility for now
        lastVisit: customer.created_at ? new Date(customer.created_at).toLocaleDateString('pt-BR') : '-',
        createdAt: customer.created_at ? new Date(customer.created_at) : undefined
    };
}
